App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"

urlpatterns = [
    path('signup/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('edit/', views.edit_profile, name='edit'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('user/<username>', views.user, name='user'),
    path('follow/<username>', views.follow, name='follow'),
    path('unfollow/<username>', views.unfollow, name='unfollow'),
]

App_Post/urls.py
from App_Post import views
from django.urls import path

app_name = 'App_Post'

urlpatterns = [
    path('', views.Home, name='home'),
    path('liked/<pk>/', views.liked, name='liked'),
    path('unliked/<pk>/', views.unliked, name='unliked'),
]

My_Social_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from App_Post import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Post.urls')),
    path('', views.Home, name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile',)
    profile_pic = models.ImageField(default="default.png", blank=True)
    description = models.TextField(blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)

    def __str__(self):
        return str(self.user)


class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created_date = models.DateTimeField(auto_now_add=True)

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User
from App_Login.models import UserProfile


class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password1 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    password2 = forms.CharField(required=True, label="", widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password '}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class EditProfile(forms.ModelForm):
    dob = forms.DateField(label="Date of Birth", widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = UserProfile
        fields = '__all__'
        exclude = ['user']

App_Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from App_Login.forms import CreateNewUser, EditProfile
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from App_Login.models import UserProfile, Follow
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from App_Post.forms import PostForm
from django.contrib.auth.models import User

# Create your views here.


def sign_up(request):
    form = CreateNewUser()
    register = False
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            register = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('App_Login:login'))
    context = {
        'title': 'Sign up | Instagram',
        'form': form,
        'register': register,
    }
    return render(request, 'App_Login/signup.html', context)


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Post:home'))

    return render(request, 'App_Login/login.html', {'title': 'Login', 'form': form})


@login_required
def edit_profile(request):
    user = request.user.user_profile
    form = EditProfile(instance=user)

    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/profile.html', context={'title': 'Edit Profile | Social', 'form': form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:login'))


@login_required
def profile(request):
    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES,)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('home'))
    return render(request, 'App_Login/user.html', {'title': 'User', 'form': form})


@login_required
def user(request, username):
    user_other = User.objects.get(username=username)
    already_followed = Follow.objects.filter(follower=request.user, following=user_other)
    if user_other == request.user:
        return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/user_other.html', {'user_other': user_other, 'already_followed': already_followed})


@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    if not already_followed:
        followed_user = Follow(follower=follower_user, following=following_user)
        followed_user.save()
    return HttpResponseRedirect(reverse('App_Login:user', kwargs={'username': username}))


@login_required
def unfollow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower = follower_user, following = following_user)
    already_followed.delete()
    return HttpResponseRedirect(reverse('App_Login:user', kwargs={'username': username}))

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}
{% block css_block %}
.signup{
border: 1px solid #ccc;
padding: 20px;
}
    {% endblock %}
{% block body_block %}

<center>
    <br>
    <div class="col-md-5 signup">
        <h3 class="font-weight-bold">Login to see photos from your Friends</h3>
        <form action="" method="POST">
        {{form|crispy}}
        {% csrf_token %}
            <button type="submit" class="btn btn-sm btn-primary">LogIn</button>
        </form>
        <div class="">
            <p>Don't have an account? <a href="{% url 'App_Login:sign_up' %}">Sign Up</a></p>
        </div>
    </div>
</center>

{% endblock %}

templates/App_Login/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}

        {% block css_block %}
<!--            .signup{-->
<!--            border: 1px solid #ccc;-->
<!--            padding: 20px;-->
<!--            }-->
        {% endblock %}

{% block body_block %}
        <form method="POST", action="", enctype="multipart/form-data">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" name="Update Information" class="btn btn-primary">
        </form>
{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}}{% endblock %}
{% block css_block %}
.signup{
border: 1px solid #ccc;
padding: 20px;
}
    {% endblock %}
{% block body_block %}
<center>
    <br>
    <div class="col-md-5 signup">
        <h3 class="font-weight-bold">Sign Up to see photos from your Friends.</h3>
        <form action="" method="POST">
        {{form|crispy}}
        {% csrf_token %}
            <button type="submit" class="btn btn-sm btn-primary">Sign Up</button>
        </form>
        <div class="">
            <p>Have an account? <a href="{% url 'App_Login:login' %}">Login</a></p>
        </div>
    </div>
</center>

{% endblock %}


templates/App_Login/user.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{user.user_profile.full_name}} @{{user.username}} {% endblock %}

        {% block css_block %}
                .profile-pic{
                    max-width: 200px;
                    max-height: 200px;
                    margin: 0 auto;
                    border-radius:50%

                    }
        {% endblock %}

{% block body_block %}
<br>
<div class="row">
    <div class="col-md-3">
        <div class="card card-body">
<!--            <a href="{% url 'home' %}" class="btn btn-warning">&#8592; Back to Profile</a>-->
<!--            <hr>-->
<!--            <h3 style="text-align: center;">Account Setting</h3>-->
<!--            <hr>-->
<!--                {% if user.user_profile.profile_pic %}-->
<!--            {% endif %}-->
                 <img src="{{request.user.user_profile.profile_pic.url}}" alt="" class="profile-pic">
            <br>
                <a href="{% url 'App_Login:edit' %}" class="btn btn-primary">&#8592; Edit Profile</a>
        </div>
    </div>

    <div class="col-md-9">
        <div class="card card-body">
                <h3>@{{user.username}}</h3>
                <h4>{{user.user_profile.full_name}}</h4>
                <h6>Date Of Birth: {{user.user_profile.dob}}</h6>


                <h6>
                    <a href="{{user.user_profile.website}}">
                        <span class="badge badge-pill badge-secondary">Website</span>
                    </a>
                    &nbsp;
                    &nbsp;
                    <a href="{{user.user_profile.facebook}}">
                        <span class="badge badge-pill badge-success">Facebook</span>
                    </a>
                </h6>

                <p>Description: {{user.user_profile.description}}</p>
                <br>
            <h4>{{user.post.count}} posts &nbsp; &nbsp; {{user.following.count}} Followers &nbsp; &nbsp; {{user.follower.count}} following</h4>
        </div>
    </div>
</div>
<hr>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
  New Post
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Post a Photo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form method="POST" action="" enctype="multipart/form-data">
              {% csrf_token %}
              {{form|crispy}}
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="Submit" class="btn btn-primary">Post</button>
              </div>
          </form>
      </div>

    </div>
  </div>
</div>
<br>
<br>
<div class="row">
    {% for post in user.post.all%}
    <div class="col-md-3">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{post.image.url}}" title="{{post.caption}}" alt="{{post.caption}}">
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/App_Login/user_other.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{user_other.user_profile.full_name}} @{{user_other.username}} {% endblock %}

        {% block css_block %}
                .profile-pic{
                    max-width: 200px;
                    max-height: 200px;
                    margin: 0 auto;
                    border-radius:50%

                    }
        {% endblock %}

{% block body_block %}
<br>
<div class="row">
    <div class="col-md-3">
        <div class="card card-body">
<!--            <a href="{% url 'home' %}" class="btn btn-warning">&#8592; Back to Profile</a>-->
<!--            <hr>-->
<!--            <h3 style="text-align: center;">Account Setting</h3>-->
<!--            <hr>-->
<!--                {% if user.user_profile.profile_pic %}-->
<!--            {% endif %}-->
                 <img src="{{request.user.user_profile.profile_pic.url}}" alt="" class="profile-pic">
            <br>
            {% if not already_followed %}
                <a href="{% url 'App_Login:follow' username=user_other.username %}" class="btn btn-light">&#8592; Follow </a>
            {% else %}
            <a href="{% url 'App_Login:unfollow' username=user_other.username %}" class="btn btn-primary">&#8592; UnFollow </a>
            {% endif %}
        </div>
    </div>

    <div class="col-md-9">
        <div class="card card-body">
                <h3>@{{user_other.username}}</h3>
                <h4>{{user_other.user_profile.full_name}}</h4>
                <h6>Date Of Birth: {{user_other.user_profile.dob}}</h6>


                <h6>
                    <a href="{{user_other.user_profile.website}}">
                        <span class="badge badge-pill badge-secondary">Website</span>
                    </a>
                    &nbsp;
                    &nbsp;
                    <a href="{{user_other.user_profile.facebook}}">
                        <span class="badge badge-pill badge-success">Facebook</span>
                    </a>
                </h6>

                <p>Description: {{user_other.user_profile.description}}</p>
                <br>
            <h4>{{user_other.post.count}} posts &nbsp; &nbsp; {{user_other.following.count}} Followers &nbsp; &nbsp; {{user_other.follower.count}} following</h4>
        </div>
    </div>
</div>
<hr>



<br>
<br>
<div class="row">
    {% for post in user_other.post.all%}
    <div class="col-md-3">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{post.image.url}}" title="{{post.caption}}" alt="{{post.caption}}">
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}