App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"

urlpatterns = [
    path('signup/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('edit/', views.edit_profile, name='edit'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('user/<username>', views.user, name='user'),
    path('follow/<username>', views.follow, name='follow'),
    path('unfollow/<username>', views.unfollow, name='unfollow'),
]

App_Post/urls.py
from App_Post import views
from django.urls import path

app_name = 'App_Post'

urlpatterns = [
    path('', views.Home, name='home'),
    path('liked/<pk>/', views.liked, name='liked'),
    path('unliked/<pk>/', views.unliked, name='unliked'),
]

My_Social_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from App_Post import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('post/', include('App_Post.urls')),
    path('', views.Home, name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Post/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Posts(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    image = models.ImageField(upload_to='post_images')
    caption = models.CharField(max_length=264, blank=True)
    upload_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-upload_date']


class Like(models.Model):
    post = models.ForeignKey(Posts, on_delete=models.CASCADE, related_name='liked_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{} : {}'.format(self.user, self.post)

App_Post/forms.py
from django import forms
from App_Post.models import Posts


class PostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['caption', 'image']

App_Post/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Login.models import UserProfile, Follow
from django.contrib.auth.models import User
from App_Post.models import Posts, Like
# Create your views here.


@login_required
def Home(request):
    following_list = Follow.objects.filter(follower=request.user)
    posts = Posts.objects.filter(author__in=following_list.values_list('following'))
    liked_post = Like.objects.filter(user=request.user)
    liked_post_list = liked_post.values_list('post', flat=True)
    print(liked_post_list)
    if request.method == 'GET':
        search = request.GET.get('search', '')
        result = User.objects.filter(username__icontains=search)
    return render(request, 'App_Post/home.html', context={
        'title': 'Home',
        'search': search,
        'result': result,
        'following_list': following_list,
        'posts': posts,
        'liked_post_list': liked_post_list,
    })


@login_required
def liked(request, pk):
    post = Posts.objects.get(pk=pk)
    already_liked = Like.objects.filter(post=post, user=request.user)
    if not already_liked:
        liked_post = Like(post=post, user=request.user)
        liked_post.save()
    return HttpResponseRedirect(reverse('home'))


@login_required
def unliked(request, pk):
    post = Posts.objects.get(pk=pk)
    already_liked = Like.objects.filter(post=post, user=request.user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('home'))

templates/App_Post/home.html
{% extends 'navbar.html' %}
{% load static %}
{% block title_block %} {{title}} {% endblock %}
{% block css_block %} {% endblock %}


{% block body_block %}


{% if search %}
 {% for user in result %}

<br>

 <div class="card">
 <div class="row">
  <a href="{% url 'App_Login:user' username=user.username %}">
  <div class="col-md-3">
   <img class="rounded float-left" width="100px" height="100px" src="{{user.user_profile.profile_pic.url}}" alt="">
  </div> </a>

  <div class="col-md-9">
   <h3><a style="text-decoration: none;" class="text-secondary" href="{% url 'App_Login:user' username=user.username %}">{{user.user_profile.full_name}} </a></h3>
   <p><a style="text-decoration: none;" href="{% url 'App_Login:user' username=user.username %}">{{user.username}} </a></p>
  </div>


</div>
</div>

<br>
 {% endfor %}
{% else %}


{% for post in posts %}
<div class="row">
 <div class="col-md-8">
<div class="card" style="width: 100%;">
  <div class="card-body">
    <h5 class="card-title"><a style="text-decoration: none;" class="text-dark" href="{% url 'App_Login:user' username=post.author %}">
<img class="rounded-circle float-left" width="40px" height="40px" src="{{user.user_profile.profile_pic.url}}" alt="">
  &nbsp; &nbsp; @{{post.author}}</a></h5>
  </div>

    <img src="{{post.image.url}}" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">
            <h6>{{post.caption}}</h6>
            <h5>{{post.liked_post.count}} Likes</h5>
            {% if post.pk in liked_post_list %}
            <a href="{% url 'App_Post:unliked' pk=post.pk %}">
                <i class="fa fa-heart" style="font-size:36px"></i>
            </a>
            {% else %}
            <a href="{% url 'App_Post:liked' pk=post.pk %}">
                <i class="fa fa-heart-o" style="font-size:36px"></i>
            </a>
            {% endif %}

        </h5>
    </div>
</div>

 </div>
    <div class="col-md-4"></div>
</div>

<br>
<br>

{% endfor %}


{% endif %}


{% endblock %}